### ISSUE TITLE
Available to display in Multilingual.

### ISSUE THREAD

**Issue by sin-to-jin** [ogasawaraShinnosuke/pdfpd#1]
- To set font-files to `/public/fonts/`, then do `.keep` file in the directory.

**Comment by sin-to-jin** [comment]
## free fonts
- preferably the last 1~2 years
- made in a solid team(ex, except for made in individual, and so on)

### IPA FONT
- http://ipafont.ipa.go.jp/node17#jp
  - Ver.003.01
  - 2015-10-16 Released

### Lisence
- http://ipafont.ipa.go.jp/ipa_font_license_v1-html#jp

### Implement

Setting `ttf`file to `conf/fonts`directory, and so to load their from controller. And furthermore to define `IPAexMincho` and so on to css file loaded in this system. JFTR, tested this implemented

``` sh
root/conf/fonts
├── ipaexg.ttf
└── ipaexm.ttf
```

``` scala
pdfGenerator.loadLocalFonts(List("fonts/ipaexg.ttf", "fonts/ipaexm.ttf").toList)
```

``` css
body {
  font-family:"@Hiragino Mincho ProN","@IPAexMincho","@MS 明朝","Hiragino Mincho ProN","IPAexMincho","serif";
}
```
